import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  commentRow: { flexDirection: "row", gap: 12, marginBottom: 20 },
  replyRow: { marginTop: 12, marginBottom: 0, gap: 10 },
  baitReplyRow: { marginTop: 8, marginBottom: 4 },
  avatarContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#2c2c2e",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarContainerSmall: { width: 24, height: 24, borderRadius: 12 },
  avatarFallback: { color: "#aeaeb2", fontWeight: "700", fontSize: 16 },
  avatarFallbackSmall: { fontSize: 12 },
  commentMain: { flex: 1 },
  commentBodyWrapper: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  commentContent: { flex: 1, marginRight: 16 },
  commentUsername: {
    color: "#8e8e93",
    fontWeight: "600",
    fontSize: 13,
    marginBottom: 4,
  },
  commentUsernameMe: { color: "#0a84ff" },
  usernameRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  menuAnchor: { position: "relative", marginLeft: 8 },
  popupMenu: {
    position: "absolute",
    top: 20,
    right: 0,
    backgroundColor: "#1c1c1e",
    borderRadius: 8,
    padding: 4,
    minWidth: 120,
    elevation: 5,
    zIndex: 1000,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  menuItemText: { color: "white", fontSize: 12, fontWeight: "500" },
  editContainer: { marginBottom: 6 },
  editInput: {
    backgroundColor: "#1c1c1e",
    color: "white",
    borderRadius: 8,
    padding: 8,
    fontSize: 14,
    minHeight: 60,
    textAlignVertical: "top",
  },
  editActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 16,
    marginTop: 8,
  },
  editCancelText: { color: "#8e8e93", fontSize: 13, fontWeight: "600" },
  editSaveText: { color: "#0a84ff", fontSize: 13, fontWeight: "600" },
  authorBadge: {
    fontSize: 10,
    color: "#0a84ff",
    fontWeight: "bold",
    backgroundColor: "rgba(10,132,255,0.1)",
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
    marginLeft: 4,
    overflow: "hidden",
  },
  mainThreadLine: {
    position: "absolute",
    left: 17,
    top: 40,
    bottom: 0,
    width: 2,
    backgroundColor: "#2c2c2e",
    zIndex: -1,
  },
  branchContainer: {
    position: "absolute",
    left: -28,
    top: -20,
    bottom: 0,
    width: 20,
  },
  branchVertical: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: "#2c2c2e",
  },
  branchVerticalLast: { bottom: "50%" },
  branchHorizontal: {
    position: "absolute",
    left: 0,
    top: "50%",
    width: 18,
    height: 2,
    backgroundColor: "#2c2c2e",
  },
  commentText: {
    color: "#e5e5ea",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 6,
  },
  timestampText: { color: "#0a84ff", fontWeight: "bold" },
  tagText: { color: "#0a84ff", fontWeight: "bold" },
  readMoreText: {
    color: "#8e8e93",
    fontSize: 13,
    fontWeight: "600",
    marginTop: -4,
    marginBottom: 6,
  },
  commentFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginTop: 2,
  },
  commentDate: { color: "#8e8e93", fontSize: 12, fontWeight: "500" },
  replyBtnText: { color: "#8e8e93", fontSize: 11, fontWeight: "700" },
  likeContainer: {
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 4,
  },
  likeButton: { alignItems: "center", gap: 4 },
  likeCountText: { fontSize: 12, color: "#8e8e93", fontWeight: "500" },
  repliesSection: { marginTop: 4 },
  viewRepliesButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
  },
  viewRepliesLine: {
    width: 24,
    height: 1,
    backgroundColor: "#3a3a3c",
    marginRight: 8,
  },
  viewRepliesText: { color: "#8e8e93", fontSize: 13, fontWeight: "600" },
  repliesList: { marginTop: 4 },
  replyLine: {
    position: "absolute",
    left: -20,
    top: -20,
    bottom: 24,
    width: 1,
    backgroundColor: "#3a3a3c",
  },
  replyUsername: { fontSize: 12 },
  replyTextContent: { fontSize: 13, lineHeight: 18, color: "#d1d1d6" },
  replyLikeCount: { fontSize: 10 },
  threadSeparator: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    marginVertical: 12,
    marginLeft: -48,
  },
});
